export const ACTIVITY_CATEGORIES: string[] = [
  'Restaurant',
  'Cafe',
  'Bar',
  'Nightclub',
  'Beach',
  'Beach Club',
  'Pool Day',
  'Museum',
  'Art Gallery',
  'Church',
  'Temple',
  'Historic Site',
  'Viewpoint/Lookout',
  'Walking Tour',
  'Guided Tour',
  'Boat Tour',
  'Hiking',
  'Snorkeling',
  'Scuba Diving',
  'Surfing',
  'Ski/Snowboard',
  'Spa/Massage',
  'Shopping',
  'Market',
  'Concert',
  'Show/Theater',
  'Sports Event',
  'Amusement Park',
  'Zoo/Aquarium',
  'National Park',
  'Photo Spot',
  'Taxi/Rideshare',
  'Moped/Scooter Rental',
  'ATV/Buggy Rental',
  'Car Rental',
  'Bike Rental',
  'Cooking Class',
  'Wine Tasting/Vineyard',
  'Cultural Experience',
  'Other',
];
